# Generated by Django 5.1.2 on 2025-02-11 10:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_remove_customer_new_column_alter_customer_email_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='password',
        ),
    ]
