# Generated by Django 5.1.2 on 2025-04-03 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_product_office_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='office_created',
            field=models.CharField(blank=True, choices=[('Office 2013', 'Office 2013'), ('Office 2024', 'Office 2024'), ('Office 2016', 'Office 2016'), ('Office 2019', 'Office 2019'), ('Office 2021', 'Office 2021'), ('Office 365', 'Office 365')], max_length=200, null=True),
        ),
    ]
