# Generated by Django 5.1.2 on 2025-02-18 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_remove_customer_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='product',
            name='img',
            field=models.ImageField(blank=True, null=True, upload_to='product_files/preview'),
        ),
        migrations.AlterField(
            model_name='product',
            name='morph',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.RemoveField(
            model_name='product',
            name='product_type',
        ),
        migrations.AddField(
            model_name='product',
            name='product_type',
            field=models.ManyToManyField(to='main.tag'),
        ),
    ]
