# Generated by Django 5.1.6 on 2025-03-05 09:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_product_file_alter_product_office_created'),
        ('main', '0003_alter_product_office_created'),
    ]

    operations = [
    ]
