# Generated by Django 5.1.6 on 2025-03-05 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_merge_20250305_1413'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='product_files'),
        ),
        migrations.AlterField(
            model_name='product',
            name='office_created',
            field=models.CharField(blank=True, choices=[('Office 2021', 'Office 2021'), ('Office 2013', 'Office 2013'), ('Office 2019', 'Office 2019'), ('Office 2016', 'Office 2016')], max_length=200, null=True),
        ),
    ]
