# Generated by Django 5.1.2 on 2025-02-19 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_customer_image_product_img_alter_product_morph_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='image',
            field=models.ImageField(blank=True, default='profile/profile_pic.png', null=True, upload_to='profile/'),
        ),
    ]
