# Generated by Django 5.2 on 2025-04-08 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_alter_product_office_created'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='error_message',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='slide_images',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='product',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('active', 'Active')], default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='product',
            name='favorite',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='product',
            name='file',
            field=models.FileField(upload_to='uploads'),
        ),
        migrations.AlterField(
            model_name='product',
            name='morph',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='product',
            name='office_created',
            field=models.CharField(blank=True, choices=[('Office 2013', 'Office 2013'), ('Office 2016', 'Office 2016'), ('Office 2019', 'Office 2019'), ('Office 2021', 'Office 2021'), ('Office 2024', 'Office 2024'), ('Office 365', 'Office 365')], max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='premium',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_name',
            field=models.CharField(max_length=200),
        ),
    ]
